services:
  agent:
    build:
      context: ./agent
    working_dir: /app
    container_name: ai_agent
    environment:
      - PORT=8000
      - FRONTIER_MODEL_URL=${FRONTIER_MODEL_URL}
      - FRONTIER_MODEL=${FRONTIER_MODEL}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
    ports:
      - "8000:8000"
    command: uv run uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}
    depends_on:
      - postgres
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai_agent_db
    environment:
      POSTGRES_USER: agent_user
      POSTGRES_PASSWORD: agent_password
      POSTGRES_DB: ai_agent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: